source 'https://rubygems.org'

ruby '3.1.2'

gem 'rails', '~> 7.2.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'rack-cors'
gem 'rack-attack'
gem 'dotenv-rails'
gem 'bootsnap', require: false

# Auth
gem 'devise'
gem 'devise-jwt'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
end

group :development do
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'letter_opener'
end

group :test do
  gem 'shoulda-matchers', '~> 5.0'
end